version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: sportmatch_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    restart: unless-stopped

  api:
    build:
      context: .
    container_name: sportmatch_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data:
